### ISSUE TITLE
Modify RequestAnalyzer Output to JSON Format

### ISSUE THREAD

**Issue by ForYourEyesOnlyyy** [IU-Capstone-Project-2024/SayNoMore#28]
### Description

The `RequestAnalyzer` currently outputs a structured message detailing the analyzed information from the user's request in a semi-colon separated string format. We need to modify this output to return the details in a JSON format for better integration and data handling. The new format should adhere to strict data types and date formatting guidelines.

**Current Output Example**

```plaintext
Arrival:01/12/2024;Return:22/12/2024;Departure:Казань;Destination:Москва;Budget:35000
```

**Required Output Format**

The output should be in JSON format as follows:

```json
{
  "Arrival": "2024-12-01",
  "Return": "2024-12-22",
  "Departure": "Казань",
  "Destination": "Москва",
  "Budget": 35000
}
```

### Specific Requirements 

1. **JSON Format**:
   - Convert the structured message output into a JSON object.
   - Ensure that the JSON keys are descriptive and match the field names (e.g., "Arrival", "Return", "Departure", "Destination", "Budget").

2. **Data Types**:
   - Dates should be in the strict `YYYY-MM-DD` format.
   - Integer values, such as budget, should be returned as integers, not strings.

3. **Handle Additional Information**:
   - The JSON format should be flexible to include any additional information fields if they are part of the processed data.

### Tasks

1. **Modify Output Functionality**:
   - Update the `RequestAnalyzer` to output the processed data in JSON format.
   - Ensure all dates are formatted as `YYYY-MM-DD`.
   - Ensure numerical values (like budget) are returned as integers.

2. **Update Unit Tests**:
   - Modify existing tests to verify the new JSON output format.
   - Add new tests if necessary to cover additional scenarios.

3. **Documentation**:
   - Update the documentation to reflect the new output format.
   - Provide examples of the JSON output in the documentation for clarity.

### Acceptance Criteria

- The `RequestAnalyzer` outputs the processed travel information in the specified JSON format.
- All date fields are in the `YYYY-MM-DD` format.
- Integer fields are returned as integers in the JSON.
- The JSON format can accommodate any additional information fields without breaking the structure.
- The updated functionality passes all relevant unit tests.

### Additional Notes

- Ensure backward compatibility is maintained where necessary, but prioritize the JSON format for new developments.
- Review the current code to identify any dependencies or parts that may be affected by this change.

---

### Checklist for Subtasks

- **Modify Output Functionality**:
  - [x] Convert the structured message output to JSON format.
  - [x] Ensure date fields are formatted as `YYYY-MM-DD`.
  - [x] Ensure numerical values (e.g., budget) are integers in the JSON.

-  **Update Unit Tests**:
  - [x] Modify existing tests to validate the new JSON output format.
  - [x] Add new tests to cover any additional scenarios with the JSON output.

-  **Documentation**:
  - [x] Update the documentation to describe the new JSON output format.
  - [x] Include JSON output examples in the documentation for user reference.
