### ISSUE TITLE
Modify RequestAnalyzer JSON Output to Use IATA Codes Instead of City Names

### ISSUE THREAD

**Issue by ForYourEyesOnlyyy** [IU-Capstone-Project-2024/SayNoMore#29]
### Description

In continuation of #28 , where we modified the `RequestAnalyzer` to output the processed information in JSON format, we now need to further enhance this functionality. The goal is to replace the city names in the JSON output with their corresponding IATA codes. This modification will facilitate better integration with airline and travel APIs that often use IATA codes for location identification.

**Current JSON Output Example**

```json
{
  "Arrival": "2024-12-01",
  "Return": "2024-12-22",
  "Departure": "Казань",
  "Destination": "Москва",
  "Budget": 35000
}
```

**Required JSON Output Format**

The output should use IATA codes instead of city names. For example:

```json
{
  "Arrival": "2024-12-01",
  "Return": "2024-12-22",
  "Departure": "KZN",
  "Destination": "MOW",
  "Budget": 35000
}
```

**Reference Materials**

- [GitHub Link 1: List of IATA codes](https://github.com/ip2location/ip2location-iata-icao)
- [GitHub Link 2: List of IATA codes](https://github.com/lxndrblz/Airports)

### Specific Requirements

1. **City Name to IATA Code Conversion**:
   - Implement a method to map city names to their corresponding IATA codes.
   - Utilize the provided reference materials or an external library to ensure accurate mapping.

2. **JSON Output Modification**:
   - Update the JSON output from the `RequestAnalyzer` to include IATA codes for "Departure" and "Destination" instead of city names.

### Tasks

1. **Implement City to IATA Code Mapping**:
   - Integrate a mapping method to convert city names to IATA codes using the reference materials.
   - Verify the accuracy of the mapping against a comprehensive list of city-IATA mappings.

2. **Modify Output Functionality**:
   - Update the `RequestAnalyzer` to replace city names with their corresponding IATA codes in the JSON output.

3. **Update Unit Tests**:
   - Modify existing tests to check the JSON output for IATA codes instead of city names.
   - Add new tests if necessary to cover scenarios with different city names and their IATA codes.

4. **Documentation**:
   - Update the documentation to reflect the change to IATA codes in the JSON output.
   - Include examples of the new JSON format with IATA codes.

### Acceptance Criteria

- The `RequestAnalyzer` outputs JSON with IATA codes for "Departure" and "Destination".
- The JSON output is verified to correctly map city names to IATA codes.
- The updated functionality passes all relevant unit tests.

### References

- [GitHub Link 1: List of IATA codes](https://github.com/ip2location/ip2location-iata-icao)
- [GitHub Link 2: List of IATA codes](https://github.com/lxndrblz/Airports)

---

### Checklist for Subtasks

- **Implement City to IATA Code Mapping**:
  - [x] Integrate a method to map city names to IATA codes.
  - [x] Verify the mapping accuracy against reference materials.

- **Modify Output Functionality**:
  - [x] Update `RequestAnalyzer` to use IATA codes in JSON output for "Departure" and "Destination".
  - [x] Ensure dates and budget formats are maintained.

- **Update Unit Tests**:
  - [x] Modify existing tests to validate the JSON output with IATA codes.
  - [x] Add new tests for different city-IATA mappings.

- **Documentation**:
  - [x] Update the documentation to reflect the use of IATA codes.
  - [x] Include examples of the JSON output with IATA codes.
