### ISSUE TITLE
Refactor `tests/unit_api_tests.py` to Address Ruff Linter Report

### ISSUE THREAD

**Issue by ForYourEyesOnlyyy** [IU-Capstone-Project-2024/SayNoMore#31]
### Description

The Ruff linter has identified an issue in the `tests/unit_api_tests.py` file where an f-string is used without any placeholders. This f-string is unnecessary and should be refactored to a regular string to maintain code quality and adhere to best practices.

**Linter Report Details:**

```plaintext
tests/unit_api_tests.py:144:21: F541 [*] f-string without any placeholders
    |
142 |     def test_fetch_hotel_photos(self):
143 |         id = [4]
144 |         file_path = f'photos/hotelPhotos/4/photo1.avif'
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ F541
145 |         # Check if the file exists
146 |         if os.path.exists(file_path):
    |
    = help: Remove extraneous `f` prefix
```

### Tasks

1. **Identify the Problematic Line**:
   - Locate the f-string in `tests/unit_api_tests.py` that does not use any placeholders.
   - Confirm that it can be safely converted to a regular string without affecting functionality.

2. **Refactor the Line**:
   - Change the f-string at line 144 to a regular string.
   - Ensure that the change does not affect the logic or functionality of the test case.

3. **Run Tests**:
   - Execute the unit tests to verify that the refactoring does not introduce any issues.
   - Ensure that all tests pass successfully after the change.

4. **Update Documentation**:
   - If there are any comments or documentation in the code referencing the f-string, update them to reflect the change to a regular string.
   - Ensure that the code documentation remains clear and accurate.

### Acceptance Criteria

- The f-string in `tests/unit_api_tests.py` is refactored to a regular string.
- All unit tests pass successfully after the refactor.
- The code adheres to Ruff linter guidelines and does not generate any linter warnings or errors related to this issue.
- Documentation, if any, is updated to reflect the changes made.

### Checklist for Subtasks

- **Identify the Problematic Line**:
  - [x] Locate the f-string without placeholders in `tests/unit_api_tests.py`.
  - [x] Confirm that it can be converted to a regular string.

- **Refactor the Line**:
  - [x] Change the f-string to a regular string.
  - [x] Verify that the functionality remains unaffected.

- **Run Tests**:
  - [x] Execute unit tests to ensure the refactoring does not cause any issues.
  - [x] Confirm that all tests pass successfully.

- **Update Documentation**:
  - [x] Update any relevant documentation or comments to reflect the change.
  - [x] Ensure clarity and accuracy in the code documentation.
